/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContributingRouteImport } from './routes/contributing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsStorageRouteImport } from './routes/docs.storage'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsRoadmapRouteImport } from './routes/docs.roadmap'
import { Route as DocsPythonSdkRouteImport } from './routes/docs.python-sdk'
import { Route as DocsProjectHistoryRouteImport } from './routes/docs.project-history'
import { Route as DocsPerformanceRouteImport } from './routes/docs.performance'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsGuidesRouteImport } from './routes/docs.guides'
import { Route as DocsGpuEngineRouteImport } from './routes/docs.gpu-engine'
import { Route as DocsGettingStartedRouteImport } from './routes/docs.getting-started'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsEqlRouteImport } from './routes/docs.eql'
import { Route as DocsDesignDecisionsRouteImport } from './routes/docs.design-decisions'
import { Route as DocsCppSdkRouteImport } from './routes/docs.cpp-sdk'
import { Route as DocsCoreConceptsRouteImport } from './routes/docs.core-concepts'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsBenchmarksRouteImport } from './routes/docs.benchmarks'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsAlgorithmsRouteImport } from './routes/docs.algorithms'
import { Route as DocsAdvancedRouteImport } from './routes/docs.advanced'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DocsTutorialIndexRouteImport } from './routes/docs.tutorial.index'
import { Route as DocsTutorialLessonRouteImport } from './routes/docs.tutorial.$lesson'
import { Route as DocsPythonWalRouteImport } from './routes/docs.python.wal'
import { Route as DocsPythonVaultRouteImport } from './routes/docs.python.vault'
import { Route as DocsPythonUtilitiesRouteImport } from './routes/docs.python.utilities'
import { Route as DocsPythonTransactionRouteImport } from './routes/docs.python.transaction'
import { Route as DocsPythonModelsRouteImport } from './routes/docs.python.models'
import { Route as DocsPythonMaintenanceRouteImport } from './routes/docs.python.maintenance'
import { Route as DocsPythonGpuRouteImport } from './routes/docs.python.gpu'
import { Route as DocsPythonFilteringRouteImport } from './routes/docs.python.filtering'
import { Route as DocsPythonErrorsRouteImport } from './routes/docs.python.errors'
import { Route as DocsPythonEqlRouteImport } from './routes/docs.python.eql'
import { Route as DocsPythonEngineRouteImport } from './routes/docs.python.engine'
import { Route as DocsPythonDurabilityRouteImport } from './routes/docs.python.durability'
import { Route as DocsPythonDatabaseRouteImport } from './routes/docs.python.database'
import { Route as DocsPythonConnectRouteImport } from './routes/docs.python.connect'
import { Route as DocsPythonConfigRouteImport } from './routes/docs.python.config'
import { Route as DocsPythonArenaRouteImport } from './routes/docs.python.arena'
import { Route as DocsInternalsTransactionEngineRouteImport } from './routes/docs.internals.transaction-engine'
import { Route as DocsInternalsLockManagerRouteImport } from './routes/docs.internals.lock-manager'
import { Route as DocsGpuOverviewRouteImport } from './routes/docs.gpu.overview'
import { Route as DocsCppVaultRouteImport } from './routes/docs.cpp.vault'
import { Route as DocsCppTransactionRouteImport } from './routes/docs.cpp.transaction'
import { Route as DocsCppOverviewRouteImport } from './routes/docs.cpp.overview'
import { Route as DocsCppElipsInstanceRouteImport } from './routes/docs.cpp.elips-instance'
import { Route as DocsCppDomainRouteImport } from './routes/docs.cpp.domain'
import { Route as DocsCppConfigRouteImport } from './routes/docs.cpp.config'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributingRoute = ContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStorageRoute = DocsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRoadmapRoute = DocsRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonSdkRoute = DocsPythonSdkRouteImport.update({
  id: '/python-sdk',
  path: '/python-sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectHistoryRoute = DocsProjectHistoryRouteImport.update({
  id: '/project-history',
  path: '/project-history',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPerformanceRoute = DocsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesRoute = DocsGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGpuEngineRoute = DocsGpuEngineRouteImport.update({
  id: '/gpu-engine',
  path: '/gpu-engine',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGettingStartedRoute = DocsGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEqlRoute = DocsEqlRouteImport.update({
  id: '/eql',
  path: '/eql',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDesignDecisionsRoute = DocsDesignDecisionsRouteImport.update({
  id: '/design-decisions',
  path: '/design-decisions',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppSdkRoute = DocsCppSdkRouteImport.update({
  id: '/cpp-sdk',
  path: '/cpp-sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCoreConceptsRoute = DocsCoreConceptsRouteImport.update({
  id: '/core-concepts',
  path: '/core-concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsBenchmarksRoute = DocsBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAlgorithmsRoute = DocsAlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdvancedRoute = DocsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => DocsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTutorialIndexRoute = DocsTutorialIndexRouteImport.update({
  id: '/tutorial/',
  path: '/tutorial/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialLessonRoute = DocsTutorialLessonRouteImport.update({
  id: '/tutorial/$lesson',
  path: '/tutorial/$lesson',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonWalRoute = DocsPythonWalRouteImport.update({
  id: '/python/wal',
  path: '/python/wal',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonVaultRoute = DocsPythonVaultRouteImport.update({
  id: '/python/vault',
  path: '/python/vault',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonUtilitiesRoute = DocsPythonUtilitiesRouteImport.update({
  id: '/python/utilities',
  path: '/python/utilities',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonTransactionRoute = DocsPythonTransactionRouteImport.update({
  id: '/python/transaction',
  path: '/python/transaction',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonModelsRoute = DocsPythonModelsRouteImport.update({
  id: '/python/models',
  path: '/python/models',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonMaintenanceRoute = DocsPythonMaintenanceRouteImport.update({
  id: '/python/maintenance',
  path: '/python/maintenance',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonGpuRoute = DocsPythonGpuRouteImport.update({
  id: '/python/gpu',
  path: '/python/gpu',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonFilteringRoute = DocsPythonFilteringRouteImport.update({
  id: '/python/filtering',
  path: '/python/filtering',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonErrorsRoute = DocsPythonErrorsRouteImport.update({
  id: '/python/errors',
  path: '/python/errors',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonEqlRoute = DocsPythonEqlRouteImport.update({
  id: '/python/eql',
  path: '/python/eql',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonEngineRoute = DocsPythonEngineRouteImport.update({
  id: '/python/engine',
  path: '/python/engine',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonDurabilityRoute = DocsPythonDurabilityRouteImport.update({
  id: '/python/durability',
  path: '/python/durability',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonDatabaseRoute = DocsPythonDatabaseRouteImport.update({
  id: '/python/database',
  path: '/python/database',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonConnectRoute = DocsPythonConnectRouteImport.update({
  id: '/python/connect',
  path: '/python/connect',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonConfigRoute = DocsPythonConfigRouteImport.update({
  id: '/python/config',
  path: '/python/config',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonArenaRoute = DocsPythonArenaRouteImport.update({
  id: '/python/arena',
  path: '/python/arena',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInternalsTransactionEngineRoute =
  DocsInternalsTransactionEngineRouteImport.update({
    id: '/internals/transaction-engine',
    path: '/internals/transaction-engine',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsInternalsLockManagerRoute =
  DocsInternalsLockManagerRouteImport.update({
    id: '/internals/lock-manager',
    path: '/internals/lock-manager',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsGpuOverviewRoute = DocsGpuOverviewRouteImport.update({
  id: '/gpu/overview',
  path: '/gpu/overview',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppVaultRoute = DocsCppVaultRouteImport.update({
  id: '/cpp/vault',
  path: '/cpp/vault',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppTransactionRoute = DocsCppTransactionRouteImport.update({
  id: '/cpp/transaction',
  path: '/cpp/transaction',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppOverviewRoute = DocsCppOverviewRouteImport.update({
  id: '/cpp/overview',
  path: '/cpp/overview',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppElipsInstanceRoute = DocsCppElipsInstanceRouteImport.update({
  id: '/cpp/elips-instance',
  path: '/cpp/elips-instance',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppDomainRoute = DocsCppDomainRouteImport.update({
  id: '/cpp/domain',
  path: '/cpp/domain',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppConfigRoute = DocsCppConfigRouteImport.update({
  id: '/cpp/config',
  path: '/cpp/config',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/cpp/config': typeof DocsCppConfigRoute
  '/docs/cpp/domain': typeof DocsCppDomainRoute
  '/docs/cpp/elips-instance': typeof DocsCppElipsInstanceRoute
  '/docs/cpp/overview': typeof DocsCppOverviewRoute
  '/docs/cpp/transaction': typeof DocsCppTransactionRoute
  '/docs/cpp/vault': typeof DocsCppVaultRoute
  '/docs/gpu/overview': typeof DocsGpuOverviewRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/python/arena': typeof DocsPythonArenaRoute
  '/docs/python/config': typeof DocsPythonConfigRoute
  '/docs/python/connect': typeof DocsPythonConnectRoute
  '/docs/python/database': typeof DocsPythonDatabaseRoute
  '/docs/python/durability': typeof DocsPythonDurabilityRoute
  '/docs/python/engine': typeof DocsPythonEngineRoute
  '/docs/python/eql': typeof DocsPythonEqlRoute
  '/docs/python/errors': typeof DocsPythonErrorsRoute
  '/docs/python/filtering': typeof DocsPythonFilteringRoute
  '/docs/python/gpu': typeof DocsPythonGpuRoute
  '/docs/python/maintenance': typeof DocsPythonMaintenanceRoute
  '/docs/python/models': typeof DocsPythonModelsRoute
  '/docs/python/transaction': typeof DocsPythonTransactionRoute
  '/docs/python/utilities': typeof DocsPythonUtilitiesRoute
  '/docs/python/vault': typeof DocsPythonVaultRoute
  '/docs/python/wal': typeof DocsPythonWalRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs': typeof DocsIndexRoute
  '/docs/cpp/config': typeof DocsCppConfigRoute
  '/docs/cpp/domain': typeof DocsCppDomainRoute
  '/docs/cpp/elips-instance': typeof DocsCppElipsInstanceRoute
  '/docs/cpp/overview': typeof DocsCppOverviewRoute
  '/docs/cpp/transaction': typeof DocsCppTransactionRoute
  '/docs/cpp/vault': typeof DocsCppVaultRoute
  '/docs/gpu/overview': typeof DocsGpuOverviewRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/python/arena': typeof DocsPythonArenaRoute
  '/docs/python/config': typeof DocsPythonConfigRoute
  '/docs/python/connect': typeof DocsPythonConnectRoute
  '/docs/python/database': typeof DocsPythonDatabaseRoute
  '/docs/python/durability': typeof DocsPythonDurabilityRoute
  '/docs/python/engine': typeof DocsPythonEngineRoute
  '/docs/python/eql': typeof DocsPythonEqlRoute
  '/docs/python/errors': typeof DocsPythonErrorsRoute
  '/docs/python/filtering': typeof DocsPythonFilteringRoute
  '/docs/python/gpu': typeof DocsPythonGpuRoute
  '/docs/python/maintenance': typeof DocsPythonMaintenanceRoute
  '/docs/python/models': typeof DocsPythonModelsRoute
  '/docs/python/transaction': typeof DocsPythonTransactionRoute
  '/docs/python/utilities': typeof DocsPythonUtilitiesRoute
  '/docs/python/vault': typeof DocsPythonVaultRoute
  '/docs/python/wal': typeof DocsPythonWalRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial': typeof DocsTutorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/benchmarks': typeof DocsBenchmarksRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/getting-started': typeof DocsGettingStartedRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/cpp/config': typeof DocsCppConfigRoute
  '/docs/cpp/domain': typeof DocsCppDomainRoute
  '/docs/cpp/elips-instance': typeof DocsCppElipsInstanceRoute
  '/docs/cpp/overview': typeof DocsCppOverviewRoute
  '/docs/cpp/transaction': typeof DocsCppTransactionRoute
  '/docs/cpp/vault': typeof DocsCppVaultRoute
  '/docs/gpu/overview': typeof DocsGpuOverviewRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/python/arena': typeof DocsPythonArenaRoute
  '/docs/python/config': typeof DocsPythonConfigRoute
  '/docs/python/connect': typeof DocsPythonConnectRoute
  '/docs/python/database': typeof DocsPythonDatabaseRoute
  '/docs/python/durability': typeof DocsPythonDurabilityRoute
  '/docs/python/engine': typeof DocsPythonEngineRoute
  '/docs/python/eql': typeof DocsPythonEqlRoute
  '/docs/python/errors': typeof DocsPythonErrorsRoute
  '/docs/python/filtering': typeof DocsPythonFilteringRoute
  '/docs/python/gpu': typeof DocsPythonGpuRoute
  '/docs/python/maintenance': typeof DocsPythonMaintenanceRoute
  '/docs/python/models': typeof DocsPythonModelsRoute
  '/docs/python/transaction': typeof DocsPythonTransactionRoute
  '/docs/python/utilities': typeof DocsPythonUtilitiesRoute
  '/docs/python/vault': typeof DocsPythonVaultRoute
  '/docs/python/wal': typeof DocsPythonWalRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/benchmarks'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs/'
    | '/docs/cpp/config'
    | '/docs/cpp/domain'
    | '/docs/cpp/elips-instance'
    | '/docs/cpp/overview'
    | '/docs/cpp/transaction'
    | '/docs/cpp/vault'
    | '/docs/gpu/overview'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/python/arena'
    | '/docs/python/config'
    | '/docs/python/connect'
    | '/docs/python/database'
    | '/docs/python/durability'
    | '/docs/python/engine'
    | '/docs/python/eql'
    | '/docs/python/errors'
    | '/docs/python/filtering'
    | '/docs/python/gpu'
    | '/docs/python/maintenance'
    | '/docs/python/models'
    | '/docs/python/transaction'
    | '/docs/python/utilities'
    | '/docs/python/vault'
    | '/docs/python/wal'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/benchmarks'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs'
    | '/docs/cpp/config'
    | '/docs/cpp/domain'
    | '/docs/cpp/elips-instance'
    | '/docs/cpp/overview'
    | '/docs/cpp/transaction'
    | '/docs/cpp/vault'
    | '/docs/gpu/overview'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/python/arena'
    | '/docs/python/config'
    | '/docs/python/connect'
    | '/docs/python/database'
    | '/docs/python/durability'
    | '/docs/python/engine'
    | '/docs/python/eql'
    | '/docs/python/errors'
    | '/docs/python/filtering'
    | '/docs/python/gpu'
    | '/docs/python/maintenance'
    | '/docs/python/models'
    | '/docs/python/transaction'
    | '/docs/python/utilities'
    | '/docs/python/vault'
    | '/docs/python/wal'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/benchmarks'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/getting-started'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs/'
    | '/docs/cpp/config'
    | '/docs/cpp/domain'
    | '/docs/cpp/elips-instance'
    | '/docs/cpp/overview'
    | '/docs/cpp/transaction'
    | '/docs/cpp/vault'
    | '/docs/gpu/overview'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/python/arena'
    | '/docs/python/config'
    | '/docs/python/connect'
    | '/docs/python/database'
    | '/docs/python/durability'
    | '/docs/python/engine'
    | '/docs/python/eql'
    | '/docs/python/errors'
    | '/docs/python/filtering'
    | '/docs/python/gpu'
    | '/docs/python/maintenance'
    | '/docs/python/models'
    | '/docs/python/transaction'
    | '/docs/python/utilities'
    | '/docs/python/vault'
    | '/docs/python/wal'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ContributingRoute: typeof ContributingRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributing': {
      id: '/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof ContributingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/storage': {
      id: '/docs/storage'
      path: '/storage'
      fullPath: '/docs/storage'
      preLoaderRoute: typeof DocsStorageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/roadmap': {
      id: '/docs/roadmap'
      path: '/roadmap'
      fullPath: '/docs/roadmap'
      preLoaderRoute: typeof DocsRoadmapRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python-sdk': {
      id: '/docs/python-sdk'
      path: '/python-sdk'
      fullPath: '/docs/python-sdk'
      preLoaderRoute: typeof DocsPythonSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/project-history': {
      id: '/docs/project-history'
      path: '/project-history'
      fullPath: '/docs/project-history'
      preLoaderRoute: typeof DocsProjectHistoryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/performance': {
      id: '/docs/performance'
      path: '/performance'
      fullPath: '/docs/performance'
      preLoaderRoute: typeof DocsPerformanceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides': {
      id: '/docs/guides'
      path: '/guides'
      fullPath: '/docs/guides'
      preLoaderRoute: typeof DocsGuidesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/gpu-engine': {
      id: '/docs/gpu-engine'
      path: '/gpu-engine'
      fullPath: '/docs/gpu-engine'
      preLoaderRoute: typeof DocsGpuEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/getting-started': {
      id: '/docs/getting-started'
      path: '/getting-started'
      fullPath: '/docs/getting-started'
      preLoaderRoute: typeof DocsGettingStartedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/eql': {
      id: '/docs/eql'
      path: '/eql'
      fullPath: '/docs/eql'
      preLoaderRoute: typeof DocsEqlRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/design-decisions': {
      id: '/docs/design-decisions'
      path: '/design-decisions'
      fullPath: '/docs/design-decisions'
      preLoaderRoute: typeof DocsDesignDecisionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp-sdk': {
      id: '/docs/cpp-sdk'
      path: '/cpp-sdk'
      fullPath: '/docs/cpp-sdk'
      preLoaderRoute: typeof DocsCppSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/core-concepts': {
      id: '/docs/core-concepts'
      path: '/core-concepts'
      fullPath: '/docs/core-concepts'
      preLoaderRoute: typeof DocsCoreConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/benchmarks': {
      id: '/docs/benchmarks'
      path: '/benchmarks'
      fullPath: '/docs/benchmarks'
      preLoaderRoute: typeof DocsBenchmarksRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/algorithms': {
      id: '/docs/algorithms'
      path: '/algorithms'
      fullPath: '/docs/algorithms'
      preLoaderRoute: typeof DocsAlgorithmsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/advanced': {
      id: '/docs/advanced'
      path: '/advanced'
      fullPath: '/docs/advanced'
      preLoaderRoute: typeof DocsAdvancedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tutorial/': {
      id: '/docs/tutorial/'
      path: '/tutorial'
      fullPath: '/docs/tutorial/'
      preLoaderRoute: typeof DocsTutorialIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial/$lesson': {
      id: '/docs/tutorial/$lesson'
      path: '/tutorial/$lesson'
      fullPath: '/docs/tutorial/$lesson'
      preLoaderRoute: typeof DocsTutorialLessonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/wal': {
      id: '/docs/python/wal'
      path: '/python/wal'
      fullPath: '/docs/python/wal'
      preLoaderRoute: typeof DocsPythonWalRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/vault': {
      id: '/docs/python/vault'
      path: '/python/vault'
      fullPath: '/docs/python/vault'
      preLoaderRoute: typeof DocsPythonVaultRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/utilities': {
      id: '/docs/python/utilities'
      path: '/python/utilities'
      fullPath: '/docs/python/utilities'
      preLoaderRoute: typeof DocsPythonUtilitiesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/transaction': {
      id: '/docs/python/transaction'
      path: '/python/transaction'
      fullPath: '/docs/python/transaction'
      preLoaderRoute: typeof DocsPythonTransactionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/models': {
      id: '/docs/python/models'
      path: '/python/models'
      fullPath: '/docs/python/models'
      preLoaderRoute: typeof DocsPythonModelsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/maintenance': {
      id: '/docs/python/maintenance'
      path: '/python/maintenance'
      fullPath: '/docs/python/maintenance'
      preLoaderRoute: typeof DocsPythonMaintenanceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/gpu': {
      id: '/docs/python/gpu'
      path: '/python/gpu'
      fullPath: '/docs/python/gpu'
      preLoaderRoute: typeof DocsPythonGpuRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/filtering': {
      id: '/docs/python/filtering'
      path: '/python/filtering'
      fullPath: '/docs/python/filtering'
      preLoaderRoute: typeof DocsPythonFilteringRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/errors': {
      id: '/docs/python/errors'
      path: '/python/errors'
      fullPath: '/docs/python/errors'
      preLoaderRoute: typeof DocsPythonErrorsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/eql': {
      id: '/docs/python/eql'
      path: '/python/eql'
      fullPath: '/docs/python/eql'
      preLoaderRoute: typeof DocsPythonEqlRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/engine': {
      id: '/docs/python/engine'
      path: '/python/engine'
      fullPath: '/docs/python/engine'
      preLoaderRoute: typeof DocsPythonEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/durability': {
      id: '/docs/python/durability'
      path: '/python/durability'
      fullPath: '/docs/python/durability'
      preLoaderRoute: typeof DocsPythonDurabilityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/database': {
      id: '/docs/python/database'
      path: '/python/database'
      fullPath: '/docs/python/database'
      preLoaderRoute: typeof DocsPythonDatabaseRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/connect': {
      id: '/docs/python/connect'
      path: '/python/connect'
      fullPath: '/docs/python/connect'
      preLoaderRoute: typeof DocsPythonConnectRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/config': {
      id: '/docs/python/config'
      path: '/python/config'
      fullPath: '/docs/python/config'
      preLoaderRoute: typeof DocsPythonConfigRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python/arena': {
      id: '/docs/python/arena'
      path: '/python/arena'
      fullPath: '/docs/python/arena'
      preLoaderRoute: typeof DocsPythonArenaRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/internals/transaction-engine': {
      id: '/docs/internals/transaction-engine'
      path: '/internals/transaction-engine'
      fullPath: '/docs/internals/transaction-engine'
      preLoaderRoute: typeof DocsInternalsTransactionEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/internals/lock-manager': {
      id: '/docs/internals/lock-manager'
      path: '/internals/lock-manager'
      fullPath: '/docs/internals/lock-manager'
      preLoaderRoute: typeof DocsInternalsLockManagerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/gpu/overview': {
      id: '/docs/gpu/overview'
      path: '/gpu/overview'
      fullPath: '/docs/gpu/overview'
      preLoaderRoute: typeof DocsGpuOverviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/vault': {
      id: '/docs/cpp/vault'
      path: '/cpp/vault'
      fullPath: '/docs/cpp/vault'
      preLoaderRoute: typeof DocsCppVaultRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/transaction': {
      id: '/docs/cpp/transaction'
      path: '/cpp/transaction'
      fullPath: '/docs/cpp/transaction'
      preLoaderRoute: typeof DocsCppTransactionRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/overview': {
      id: '/docs/cpp/overview'
      path: '/cpp/overview'
      fullPath: '/docs/cpp/overview'
      preLoaderRoute: typeof DocsCppOverviewRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/elips-instance': {
      id: '/docs/cpp/elips-instance'
      path: '/cpp/elips-instance'
      fullPath: '/docs/cpp/elips-instance'
      preLoaderRoute: typeof DocsCppElipsInstanceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/domain': {
      id: '/docs/cpp/domain'
      path: '/cpp/domain'
      fullPath: '/docs/cpp/domain'
      preLoaderRoute: typeof DocsCppDomainRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp/config': {
      id: '/docs/cpp/config'
      path: '/cpp/config'
      fullPath: '/docs/cpp/config'
      preLoaderRoute: typeof DocsCppConfigRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAdvancedRoute: typeof DocsAdvancedRoute
  DocsAlgorithmsRoute: typeof DocsAlgorithmsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsBenchmarksRoute: typeof DocsBenchmarksRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsCoreConceptsRoute: typeof DocsCoreConceptsRoute
  DocsCppSdkRoute: typeof DocsCppSdkRoute
  DocsDesignDecisionsRoute: typeof DocsDesignDecisionsRoute
  DocsEqlRoute: typeof DocsEqlRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsGettingStartedRoute: typeof DocsGettingStartedRoute
  DocsGpuEngineRoute: typeof DocsGpuEngineRoute
  DocsGuidesRoute: typeof DocsGuidesRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPerformanceRoute: typeof DocsPerformanceRoute
  DocsProjectHistoryRoute: typeof DocsProjectHistoryRoute
  DocsPythonSdkRoute: typeof DocsPythonSdkRoute
  DocsRoadmapRoute: typeof DocsRoadmapRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsStorageRoute: typeof DocsStorageRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsCppConfigRoute: typeof DocsCppConfigRoute
  DocsCppDomainRoute: typeof DocsCppDomainRoute
  DocsCppElipsInstanceRoute: typeof DocsCppElipsInstanceRoute
  DocsCppOverviewRoute: typeof DocsCppOverviewRoute
  DocsCppTransactionRoute: typeof DocsCppTransactionRoute
  DocsCppVaultRoute: typeof DocsCppVaultRoute
  DocsGpuOverviewRoute: typeof DocsGpuOverviewRoute
  DocsInternalsLockManagerRoute: typeof DocsInternalsLockManagerRoute
  DocsInternalsTransactionEngineRoute: typeof DocsInternalsTransactionEngineRoute
  DocsPythonArenaRoute: typeof DocsPythonArenaRoute
  DocsPythonConfigRoute: typeof DocsPythonConfigRoute
  DocsPythonConnectRoute: typeof DocsPythonConnectRoute
  DocsPythonDatabaseRoute: typeof DocsPythonDatabaseRoute
  DocsPythonDurabilityRoute: typeof DocsPythonDurabilityRoute
  DocsPythonEngineRoute: typeof DocsPythonEngineRoute
  DocsPythonEqlRoute: typeof DocsPythonEqlRoute
  DocsPythonErrorsRoute: typeof DocsPythonErrorsRoute
  DocsPythonFilteringRoute: typeof DocsPythonFilteringRoute
  DocsPythonGpuRoute: typeof DocsPythonGpuRoute
  DocsPythonMaintenanceRoute: typeof DocsPythonMaintenanceRoute
  DocsPythonModelsRoute: typeof DocsPythonModelsRoute
  DocsPythonTransactionRoute: typeof DocsPythonTransactionRoute
  DocsPythonUtilitiesRoute: typeof DocsPythonUtilitiesRoute
  DocsPythonVaultRoute: typeof DocsPythonVaultRoute
  DocsPythonWalRoute: typeof DocsPythonWalRoute
  DocsTutorialLessonRoute: typeof DocsTutorialLessonRoute
  DocsTutorialIndexRoute: typeof DocsTutorialIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAdvancedRoute: DocsAdvancedRoute,
  DocsAlgorithmsRoute: DocsAlgorithmsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsBenchmarksRoute: DocsBenchmarksRoute,
  DocsCliRoute: DocsCliRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsCoreConceptsRoute: DocsCoreConceptsRoute,
  DocsCppSdkRoute: DocsCppSdkRoute,
  DocsDesignDecisionsRoute: DocsDesignDecisionsRoute,
  DocsEqlRoute: DocsEqlRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsGettingStartedRoute: DocsGettingStartedRoute,
  DocsGpuEngineRoute: DocsGpuEngineRoute,
  DocsGuidesRoute: DocsGuidesRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPerformanceRoute: DocsPerformanceRoute,
  DocsProjectHistoryRoute: DocsProjectHistoryRoute,
  DocsPythonSdkRoute: DocsPythonSdkRoute,
  DocsRoadmapRoute: DocsRoadmapRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsStorageRoute: DocsStorageRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsCppConfigRoute: DocsCppConfigRoute,
  DocsCppDomainRoute: DocsCppDomainRoute,
  DocsCppElipsInstanceRoute: DocsCppElipsInstanceRoute,
  DocsCppOverviewRoute: DocsCppOverviewRoute,
  DocsCppTransactionRoute: DocsCppTransactionRoute,
  DocsCppVaultRoute: DocsCppVaultRoute,
  DocsGpuOverviewRoute: DocsGpuOverviewRoute,
  DocsInternalsLockManagerRoute: DocsInternalsLockManagerRoute,
  DocsInternalsTransactionEngineRoute: DocsInternalsTransactionEngineRoute,
  DocsPythonArenaRoute: DocsPythonArenaRoute,
  DocsPythonConfigRoute: DocsPythonConfigRoute,
  DocsPythonConnectRoute: DocsPythonConnectRoute,
  DocsPythonDatabaseRoute: DocsPythonDatabaseRoute,
  DocsPythonDurabilityRoute: DocsPythonDurabilityRoute,
  DocsPythonEngineRoute: DocsPythonEngineRoute,
  DocsPythonEqlRoute: DocsPythonEqlRoute,
  DocsPythonErrorsRoute: DocsPythonErrorsRoute,
  DocsPythonFilteringRoute: DocsPythonFilteringRoute,
  DocsPythonGpuRoute: DocsPythonGpuRoute,
  DocsPythonMaintenanceRoute: DocsPythonMaintenanceRoute,
  DocsPythonModelsRoute: DocsPythonModelsRoute,
  DocsPythonTransactionRoute: DocsPythonTransactionRoute,
  DocsPythonUtilitiesRoute: DocsPythonUtilitiesRoute,
  DocsPythonVaultRoute: DocsPythonVaultRoute,
  DocsPythonWalRoute: DocsPythonWalRoute,
  DocsTutorialLessonRoute: DocsTutorialLessonRoute,
  DocsTutorialIndexRoute: DocsTutorialIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ContributingRoute: ContributingRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
