"""Packaging invariants for the ELIPS source distribution.

The C++ engine lives at the repository root, outside the Python package, so an
sdist has to carry its own copy under ``core_src/``. Two things went wrong with
the original arrangement and both are pinned here:

- the copy was made at ``setup.py`` *import* time, so merely importing the file
  deleted and rewrote a directory tree;
- the copy was untracked and silently went stale, ending up without
  ``quant_engine/`` -- which ``elips_core`` cannot build without.

These tests read ``setup.py`` as data rather than executing it, so they need
neither setuptools nor a compiler.
"""

from __future__ import annotations

import ast
import pathlib

import pytest

SETUP_PY = (
    pathlib.Path(__file__).resolve().parents[2] / "bindings" / "python" / "setup.py"
)


@pytest.fixture(scope="module")
def setup_module_body() -> list[ast.stmt]:
    return ast.parse(SETUP_PY.read_text()).body


def test_setup_py_has_no_import_time_side_effects(
    setup_module_body: list[ast.stmt],
) -> None:
    """Nothing at module scope may touch the filesystem.

    ``pip``, ``build``, and editors all import ``setup.py`` routinely. A
    ``shutil.rmtree`` at module scope turns any of those into a destructive
    operation.
    """

    destructive = {"rmtree", "copytree", "copy2", "mkdir", "unlink", "rmdir", "remove"}
    offenders: list[str] = []

    for node in setup_module_body:
        # Definitions and imports are inert; only executable statements at
        # module scope can have a side effect on import.
        if isinstance(
            node,
            (
                ast.FunctionDef,
                ast.AsyncFunctionDef,
                ast.ClassDef,
                ast.Import,
                ast.ImportFrom,
            ),
        ):
            continue
        for call in (n for n in ast.walk(node) if isinstance(n, ast.Call)):
            func = call.func
            name = (
                func.attr
                if isinstance(func, ast.Attribute)
                else getattr(func, "id", "")
            )
            if name in destructive:
                offenders.append(f"line {call.lineno}: {name}()")

    assert not offenders, (
        "setup.py mutates the filesystem at import time: " + ", ".join(offenders)
    )


def test_vendored_paths_cover_everything_the_build_needs(
    setup_module_body: list[ast.stmt],
) -> None:
    """``VENDORED_PATHS`` must carry every source ``elips_core`` compiles.

    ``quant_engine/`` is the specific directory the stale hand-made copy was
    missing, which made the resulting sdist fail to compile.
    """

    vendored: tuple[str, ...] = ()
    for node in setup_module_body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "VENDORED_PATHS" for t in node.targets
        ):
            vendored = tuple(ast.literal_eval(node.value))

    assert vendored, "setup.py no longer declares VENDORED_PATHS"

    repo_root = SETUP_PY.parents[2]
    cmakelists = (repo_root / "CMakeLists.txt").read_text()

    # Every source file CMake hands to add_library(elips_core ...) has to be
    # reachable from one of the vendored roots.
    core_block = cmakelists.split("add_library(elips_core", 1)[1].split(")", 1)[0]
    sources = [
        line.strip()
        for line in core_block.splitlines()
        if line.strip().endswith(".cpp")
    ]
    assert sources, "could not parse elips_core sources out of CMakeLists.txt"

    missing = [
        source
        for source in sources
        if not any(source == root or source.startswith(f"{root}/") for root in vendored)
    ]
    assert not missing, f"sources outside VENDORED_PATHS: {missing}"

    # And the roots must actually exist to be copied.
    absent = [root for root in vendored if not (repo_root / root).exists()]
    assert not absent, f"VENDORED_PATHS names paths that do not exist: {absent}"


def test_core_src_is_not_checked_into_the_repository() -> None:
    """The vendored copy is a build artifact, generated by ``sdist``."""

    assert not (SETUP_PY.parent / "core_src").exists(), (
        "bindings/python/core_src/ is a generated artifact and should not be "
        "present in a checkout; it is created by `setup.py sdist`"
    )
