from typing import Iterable, Mapping, Sequence

MetaValue = bool | int | float | str
Vector = Sequence[float]

class ElipsError(Exception): ...
class LockConflict(ElipsError): ...

class Result:
    @property
    def id(self) -> str: ...
    @property
    def distance(self) -> float: ...
    @property
    def data(self) -> dict[str, MetaValue]: ...

class Filter:
    def __init__(self) -> None: ...
    def field(self, name: str) -> "Filter": ...
    def equals(self, value: MetaValue) -> "Filter": ...
    def not_equals(self, value: MetaValue) -> "Filter": ...
    def lt(self, value: MetaValue) -> "Filter": ...
    def le(self, value: MetaValue) -> "Filter": ...
    def gt(self, value: MetaValue) -> "Filter": ...
    def gte(self, value: MetaValue) -> "Filter": ...
    def one_of(self, values: Iterable[MetaValue]) -> "Filter": ...
    def contains(self, substring: str) -> "Filter": ...
    def and_(self, other: "Filter") -> "Filter": ...
    def or_(self, other: "Filter") -> "Filter": ...
    @staticmethod
    def not_(inner: "Filter") -> "Filter": ...

class Vault:
    def place(
        self,
        vector: Vector,
        data: Mapping[str, MetaValue] = ...,
        id: str | None = ...,
    ) -> str: ...
    def seek(
        self,
        vector: Vector,
        top: int = ...,
        where: Filter = ...,
        threshold: float | None = ...,
    ) -> list[Result]: ...
    def fetch(self, id: str) -> dict[str, MetaValue] | None: ...
    def erase(self, id: str) -> bool: ...
    def scan(self, where: Filter = ...) -> list[dict[str, object]]: ...
    def count(self) -> int: ...

class Database:
    def vault(self, name: str) -> Vault: ...
    def list_vaults(self) -> list[str]: ...
    def checkpoint(self) -> None: ...
    def close(self) -> None: ...
    def query(
        self, eql: str, bindings: Mapping[str, Vector] = ...
    ) -> list[Result]: ...
    def __enter__(self) -> "Database": ...
    def __exit__(self, *args: object) -> None: ...

def open(
    path: str,
    dimension: int = ...,
    metric: str = ...,
    index: str = ...,
) -> Database: ...
