from __future__ import annotations

r"""ELIPS low-level binding facade.

This module re-exports the compiled :mod:`elips._core` extension through a
regular Python module so the package root can stay small and the low-level
runtime API remains easy to import directly.

Examples::

    >>> import elips.core as core
    >>> db = core.open(":memory:", dimension=2, metric="cosine")
    >>> docs = db.vault("documents")
    >>> docs.count()
    0
"""

from . import _core as _native_core
from ._core import (
    AccessMode,
    ChunkInfo,
    Comparator,
    Config,
    ConfigError,
    Database,
    DeleteStatement,
    DimensionMismatch,
    DocumentAttachment,
    Durability,
    ElipsError,
    EmbeddingLineage,
    FetchStatement,
    Filter,
    GraphParams,
    IndexSnapshot,
    IndexSnapshotKind,
    IndexType,
    InsertStatement,
    InvalidVector,
    IvfSnapshot,
    LocalEmbedderConfig,
    LockConflict,
    Metric,
    NotFound,
    ParseError,
    PqSnapshot,
    QueryPlan,
    QueryStrategy,
    Result,
    ScanStatement,
    SearchStatement,
    StorageError,
    TextEmbedderInfo,
    TextEmbedderKind,
    Token,
    TokenKind,
    Transaction,
    TransactionVault,
    Vault,
    VaultInfo,
    VectorRef,
    WalEntry,
    WalOp,
    describe_local_embedder,
    distance,
    generate_id,
    is_valid_id,
    magnitude,
    metric_from_string,
    metric_to_string,
    normalize,
    open,
    open_with_config,
    parse_eql,
    replay_wal,
    requires_normalization,
    tokenize_eql,
    validate_eql,
)

__version__ = _native_core.__version__

try:
    from ._core import (
        BatchStats,
        GpuConfig,
        GpuDevice,
        GpuDeviceInfo,
        GpuError,
        GpuIndexAlgorithm,
        GpuIndexBuildParams,
        GpuMemory,
        GpuMetricsSnapshot,
        GpuPolicy,
        GpuPrecision,
        GpuProfiler,
        GraphBuildAlgo,
        GraphIndexBuildParams,
        IndexBuildMode,
        IvfPqBuildParams,
        KernelTiming,
        gpu_can_fit_index,
        gpu_cpu_fallback_info,
        gpu_devices,
        gpu_error_message,
        gpu_runtime_device_info,
        gpu_select,
    )
except ImportError:
    _has_gpu = False
    _gpu_exports: list[str] = []
else:
    _has_gpu = True
    _gpu_exports = [
        "BatchStats",
        "GpuConfig",
        "GpuDevice",
        "GpuDeviceInfo",
        "GpuError",
        "GpuIndexAlgorithm",
        "GpuIndexBuildParams",
        "GpuMemory",
        "GpuMetricsSnapshot",
        "GpuPolicy",
        "GpuPrecision",
        "GpuProfiler",
        "GraphBuildAlgo",
        "GraphIndexBuildParams",
        "IndexBuildMode",
        "IvfPqBuildParams",
        "KernelTiming",
        "gpu_can_fit_index",
        "gpu_cpu_fallback_info",
        "gpu_devices",
        "gpu_error_message",
        "gpu_runtime_device_info",
        "gpu_select",
    ]

__all__ = [
    "open",
    "open_with_config",
    "Database",
    "Vault",
    "VaultInfo",
    "Filter",
    "Result",
    "Config",
    "GraphParams",
    "LocalEmbedderConfig",
    "Transaction",
    "TransactionVault",
    "TextEmbedderInfo",
    "Metric",
    "IndexType",
    "Durability",
    "AccessMode",
    "Comparator",
    "QueryStrategy",
    "TextEmbedderKind",
    "Token",
    "TokenKind",
    "validate_eql",
    "tokenize_eql",
    "parse_eql",
    "SearchStatement",
    "FetchStatement",
    "ScanStatement",
    "InsertStatement",
    "DeleteStatement",
    "VectorRef",
    "replay_wal",
    "WalEntry",
    "WalOp",
    "IndexSnapshot",
    "IndexSnapshotKind",
    "IvfSnapshot",
    "PqSnapshot",
    "describe_local_embedder",
    "generate_id",
    "is_valid_id",
    "normalize",
    "magnitude",
    "distance",
    "requires_normalization",
    "metric_from_string",
    "metric_to_string",
    "ElipsError",
    "DimensionMismatch",
    "InvalidVector",
    "ConfigError",
    "NotFound",
    "StorageError",
    "LockConflict",
    "ParseError",
    "DocumentAttachment",
    "ChunkInfo",
    "EmbeddingLineage",
    "QueryPlan",
]
__all__.extend(_gpu_exports)
