"""Type stubs for the ELIPS low-level binding facade.

The runtime module imports the GPU symbols inside a ``try``, so that a build
without GPU support still imports cleanly. Type checkers cannot see through
that, which would make every GPU call site an error. This stub declares the
full surface unconditionally: on a CPU-only build the names are absent at
runtime and guarded by ``_has_gpu``, which is the documented contract.
"""

from ._core import (
    AccessMode as AccessMode,
    BatchStats as BatchStats,
    ChunkInfo as ChunkInfo,
    Comparator as Comparator,
    Config as Config,
    ConfigError as ConfigError,
    Database as Database,
    DeleteStatement as DeleteStatement,
    DimensionMismatch as DimensionMismatch,
    DocumentAttachment as DocumentAttachment,
    Durability as Durability,
    ElipsError as ElipsError,
    EmbeddingLineage as EmbeddingLineage,
    FetchStatement as FetchStatement,
    Filter as Filter,
    GpuConfig as GpuConfig,
    GpuDevice as GpuDevice,
    GpuDeviceInfo as GpuDeviceInfo,
    GpuError as GpuError,
    GpuIndexAlgorithm as GpuIndexAlgorithm,
    GpuIndexBuildParams as GpuIndexBuildParams,
    GpuMemory as GpuMemory,
    GpuMetricsSnapshot as GpuMetricsSnapshot,
    GpuPolicy as GpuPolicy,
    GpuPrecision as GpuPrecision,
    GpuProfiler as GpuProfiler,
    GraphBuildAlgo as GraphBuildAlgo,
    GraphIndexBuildParams as GraphIndexBuildParams,
    GraphParams as GraphParams,
    IndexBuildMode as IndexBuildMode,
    IndexSnapshot as IndexSnapshot,
    IndexSnapshotKind as IndexSnapshotKind,
    IndexType as IndexType,
    InsertStatement as InsertStatement,
    InvalidVector as InvalidVector,
    IvfPqBuildParams as IvfPqBuildParams,
    IvfSnapshot as IvfSnapshot,
    KernelTiming as KernelTiming,
    LocalEmbedderConfig as LocalEmbedderConfig,
    LockConflict as LockConflict,
    Metric as Metric,
    NotFound as NotFound,
    ParseError as ParseError,
    PqSnapshot as PqSnapshot,
    QueryPlan as QueryPlan,
    QueryStrategy as QueryStrategy,
    Result as Result,
    ScanStatement as ScanStatement,
    SearchStatement as SearchStatement,
    Statement as Statement,
    StorageError as StorageError,
    TextEmbedderInfo as TextEmbedderInfo,
    TextEmbedderKind as TextEmbedderKind,
    Token as Token,
    TokenKind as TokenKind,
    Transaction as Transaction,
    TransactionVault as TransactionVault,
    Vault as Vault,
    VaultInfo as VaultInfo,
    VectorRef as VectorRef,
    WalEntry as WalEntry,
    WalOp as WalOp,
    describe_local_embedder as describe_local_embedder,
    distance as distance,
    generate_id as generate_id,
    gpu_can_fit_index as gpu_can_fit_index,
    gpu_cpu_fallback_info as gpu_cpu_fallback_info,
    gpu_devices as gpu_devices,
    gpu_error_message as gpu_error_message,
    gpu_runtime_device_info as gpu_runtime_device_info,
    gpu_select as gpu_select,
    is_valid_id as is_valid_id,
    magnitude as magnitude,
    metric_from_string as metric_from_string,
    metric_to_string as metric_to_string,
    normalize as normalize,
    open as open,
    open_with_config as open_with_config,
    parse_eql as parse_eql,
    replay_wal as replay_wal,
    requires_normalization as requires_normalization,
    tokenize_eql as tokenize_eql,
    validate_eql as validate_eql,
)

__version__: str
_has_gpu: bool
"""False when this build has no GPU backend, in which case the ``Gpu*`` names
and ``gpu_*`` functions are absent at runtime."""

__all__: list[str]
