/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContributingRouteImport } from './routes/contributing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsStorageRouteImport } from './routes/docs.storage'
import { Route as DocsSecurityRouteImport } from './routes/docs.security'
import { Route as DocsRoadmapRouteImport } from './routes/docs.roadmap'
import { Route as DocsPythonSdkRouteImport } from './routes/docs.python-sdk'
import { Route as DocsProjectHistoryRouteImport } from './routes/docs.project-history'
import { Route as DocsPerformanceRouteImport } from './routes/docs.performance'
import { Route as DocsInstallationRouteImport } from './routes/docs.installation'
import { Route as DocsGuidesRouteImport } from './routes/docs.guides'
import { Route as DocsGpuEngineRouteImport } from './routes/docs.gpu-engine'
import { Route as DocsExamplesRouteImport } from './routes/docs.examples'
import { Route as DocsEqlRouteImport } from './routes/docs.eql'
import { Route as DocsDesignDecisionsRouteImport } from './routes/docs.design-decisions'
import { Route as DocsCppSdkRouteImport } from './routes/docs.cpp-sdk'
import { Route as DocsCoreConceptsRouteImport } from './routes/docs.core-concepts'
import { Route as DocsConfigurationRouteImport } from './routes/docs.configuration'
import { Route as DocsCliRouteImport } from './routes/docs.cli'
import { Route as DocsArchitectureRouteImport } from './routes/docs.architecture'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DocsAlgorithmsRouteImport } from './routes/docs.algorithms'
import { Route as DocsAdvancedRouteImport } from './routes/docs.advanced'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DocsTutorialIndexRouteImport } from './routes/docs.tutorial.index'
import { Route as DocsTutorialLessonRouteImport } from './routes/docs.tutorial.$lesson'
import { Route as DocsInternalsTransactionEngineRouteImport } from './routes/docs.internals.transaction-engine'
import { Route as DocsInternalsLockManagerRouteImport } from './routes/docs.internals.lock-manager'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributingRoute = ContributingRouteImport.update({
  id: '/contributing',
  path: '/contributing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsStorageRoute = DocsStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DocsRoute,
} as any)
const DocsSecurityRoute = DocsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => DocsRoute,
} as any)
const DocsRoadmapRoute = DocsRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPythonSdkRoute = DocsPythonSdkRouteImport.update({
  id: '/python-sdk',
  path: '/python-sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProjectHistoryRoute = DocsProjectHistoryRouteImport.update({
  id: '/project-history',
  path: '/project-history',
  getParentRoute: () => DocsRoute,
} as any)
const DocsPerformanceRoute = DocsPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInstallationRoute = DocsInstallationRouteImport.update({
  id: '/installation',
  path: '/installation',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGuidesRoute = DocsGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => DocsRoute,
} as any)
const DocsGpuEngineRoute = DocsGpuEngineRouteImport.update({
  id: '/gpu-engine',
  path: '/gpu-engine',
  getParentRoute: () => DocsRoute,
} as any)
const DocsExamplesRoute = DocsExamplesRouteImport.update({
  id: '/examples',
  path: '/examples',
  getParentRoute: () => DocsRoute,
} as any)
const DocsEqlRoute = DocsEqlRouteImport.update({
  id: '/eql',
  path: '/eql',
  getParentRoute: () => DocsRoute,
} as any)
const DocsDesignDecisionsRoute = DocsDesignDecisionsRouteImport.update({
  id: '/design-decisions',
  path: '/design-decisions',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCppSdkRoute = DocsCppSdkRouteImport.update({
  id: '/cpp-sdk',
  path: '/cpp-sdk',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCoreConceptsRoute = DocsCoreConceptsRouteImport.update({
  id: '/core-concepts',
  path: '/core-concepts',
  getParentRoute: () => DocsRoute,
} as any)
const DocsConfigurationRoute = DocsConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DocsRoute,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/cli',
  path: '/cli',
  getParentRoute: () => DocsRoute,
} as any)
const DocsArchitectureRoute = DocsArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => DocsRoute,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAlgorithmsRoute = DocsAlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => DocsRoute,
} as any)
const DocsAdvancedRoute = DocsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => DocsRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsTutorialIndexRoute = DocsTutorialIndexRouteImport.update({
  id: '/tutorial/',
  path: '/tutorial/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsTutorialLessonRoute = DocsTutorialLessonRouteImport.update({
  id: '/tutorial/$lesson',
  path: '/tutorial/$lesson',
  getParentRoute: () => DocsRoute,
} as any)
const DocsInternalsTransactionEngineRoute =
  DocsInternalsTransactionEngineRouteImport.update({
    id: '/internals/transaction-engine',
    path: '/internals/transaction-engine',
    getParentRoute: () => DocsRoute,
  } as any)
const DocsInternalsLockManagerRoute =
  DocsInternalsLockManagerRouteImport.update({
    id: '/internals/lock-manager',
    path: '/internals/lock-manager',
    getParentRoute: () => DocsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs': typeof DocsIndexRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial': typeof DocsTutorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/chat': typeof ChatRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/contributing': typeof ContributingRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/docs/advanced': typeof DocsAdvancedRoute
  '/docs/algorithms': typeof DocsAlgorithmsRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/architecture': typeof DocsArchitectureRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/configuration': typeof DocsConfigurationRoute
  '/docs/core-concepts': typeof DocsCoreConceptsRoute
  '/docs/cpp-sdk': typeof DocsCppSdkRoute
  '/docs/design-decisions': typeof DocsDesignDecisionsRoute
  '/docs/eql': typeof DocsEqlRoute
  '/docs/examples': typeof DocsExamplesRoute
  '/docs/gpu-engine': typeof DocsGpuEngineRoute
  '/docs/guides': typeof DocsGuidesRoute
  '/docs/installation': typeof DocsInstallationRoute
  '/docs/performance': typeof DocsPerformanceRoute
  '/docs/project-history': typeof DocsProjectHistoryRoute
  '/docs/python-sdk': typeof DocsPythonSdkRoute
  '/docs/roadmap': typeof DocsRoadmapRoute
  '/docs/security': typeof DocsSecurityRoute
  '/docs/storage': typeof DocsStorageRoute
  '/docs/': typeof DocsIndexRoute
  '/docs/internals/lock-manager': typeof DocsInternalsLockManagerRoute
  '/docs/internals/transaction-engine': typeof DocsInternalsTransactionEngineRoute
  '/docs/tutorial/$lesson': typeof DocsTutorialLessonRoute
  '/docs/tutorial/': typeof DocsTutorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs/'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/chat'
    | '/community'
    | '/contact'
    | '/contributing'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/help'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/api/chat'
    | '/docs/advanced'
    | '/docs/algorithms'
    | '/docs/api'
    | '/docs/architecture'
    | '/docs/cli'
    | '/docs/configuration'
    | '/docs/core-concepts'
    | '/docs/cpp-sdk'
    | '/docs/design-decisions'
    | '/docs/eql'
    | '/docs/examples'
    | '/docs/gpu-engine'
    | '/docs/guides'
    | '/docs/installation'
    | '/docs/performance'
    | '/docs/project-history'
    | '/docs/python-sdk'
    | '/docs/roadmap'
    | '/docs/security'
    | '/docs/storage'
    | '/docs/'
    | '/docs/internals/lock-manager'
    | '/docs/internals/transaction-engine'
    | '/docs/tutorial/$lesson'
    | '/docs/tutorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  ChatRoute: typeof ChatRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  ContributingRoute: typeof ContributingRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributing': {
      id: '/contributing'
      path: '/contributing'
      fullPath: '/contributing'
      preLoaderRoute: typeof ContributingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/storage': {
      id: '/docs/storage'
      path: '/storage'
      fullPath: '/docs/storage'
      preLoaderRoute: typeof DocsStorageRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/security': {
      id: '/docs/security'
      path: '/security'
      fullPath: '/docs/security'
      preLoaderRoute: typeof DocsSecurityRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/roadmap': {
      id: '/docs/roadmap'
      path: '/roadmap'
      fullPath: '/docs/roadmap'
      preLoaderRoute: typeof DocsRoadmapRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/python-sdk': {
      id: '/docs/python-sdk'
      path: '/python-sdk'
      fullPath: '/docs/python-sdk'
      preLoaderRoute: typeof DocsPythonSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/project-history': {
      id: '/docs/project-history'
      path: '/project-history'
      fullPath: '/docs/project-history'
      preLoaderRoute: typeof DocsProjectHistoryRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/performance': {
      id: '/docs/performance'
      path: '/performance'
      fullPath: '/docs/performance'
      preLoaderRoute: typeof DocsPerformanceRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/installation': {
      id: '/docs/installation'
      path: '/installation'
      fullPath: '/docs/installation'
      preLoaderRoute: typeof DocsInstallationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/guides': {
      id: '/docs/guides'
      path: '/guides'
      fullPath: '/docs/guides'
      preLoaderRoute: typeof DocsGuidesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/gpu-engine': {
      id: '/docs/gpu-engine'
      path: '/gpu-engine'
      fullPath: '/docs/gpu-engine'
      preLoaderRoute: typeof DocsGpuEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/examples': {
      id: '/docs/examples'
      path: '/examples'
      fullPath: '/docs/examples'
      preLoaderRoute: typeof DocsExamplesRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/eql': {
      id: '/docs/eql'
      path: '/eql'
      fullPath: '/docs/eql'
      preLoaderRoute: typeof DocsEqlRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/design-decisions': {
      id: '/docs/design-decisions'
      path: '/design-decisions'
      fullPath: '/docs/design-decisions'
      preLoaderRoute: typeof DocsDesignDecisionsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cpp-sdk': {
      id: '/docs/cpp-sdk'
      path: '/cpp-sdk'
      fullPath: '/docs/cpp-sdk'
      preLoaderRoute: typeof DocsCppSdkRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/core-concepts': {
      id: '/docs/core-concepts'
      path: '/core-concepts'
      fullPath: '/docs/core-concepts'
      preLoaderRoute: typeof DocsCoreConceptsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/configuration': {
      id: '/docs/configuration'
      path: '/configuration'
      fullPath: '/docs/configuration'
      preLoaderRoute: typeof DocsConfigurationRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/architecture': {
      id: '/docs/architecture'
      path: '/architecture'
      fullPath: '/docs/architecture'
      preLoaderRoute: typeof DocsArchitectureRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/algorithms': {
      id: '/docs/algorithms'
      path: '/algorithms'
      fullPath: '/docs/algorithms'
      preLoaderRoute: typeof DocsAlgorithmsRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/advanced': {
      id: '/docs/advanced'
      path: '/advanced'
      fullPath: '/docs/advanced'
      preLoaderRoute: typeof DocsAdvancedRouteImport
      parentRoute: typeof DocsRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/tutorial/': {
      id: '/docs/tutorial/'
      path: '/tutorial'
      fullPath: '/docs/tutorial/'
      preLoaderRoute: typeof DocsTutorialIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/tutorial/$lesson': {
      id: '/docs/tutorial/$lesson'
      path: '/tutorial/$lesson'
      fullPath: '/docs/tutorial/$lesson'
      preLoaderRoute: typeof DocsTutorialLessonRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/internals/transaction-engine': {
      id: '/docs/internals/transaction-engine'
      path: '/internals/transaction-engine'
      fullPath: '/docs/internals/transaction-engine'
      preLoaderRoute: typeof DocsInternalsTransactionEngineRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/internals/lock-manager': {
      id: '/docs/internals/lock-manager'
      path: '/internals/lock-manager'
      fullPath: '/docs/internals/lock-manager'
      preLoaderRoute: typeof DocsInternalsLockManagerRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsAdvancedRoute: typeof DocsAdvancedRoute
  DocsAlgorithmsRoute: typeof DocsAlgorithmsRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsArchitectureRoute: typeof DocsArchitectureRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsConfigurationRoute: typeof DocsConfigurationRoute
  DocsCoreConceptsRoute: typeof DocsCoreConceptsRoute
  DocsCppSdkRoute: typeof DocsCppSdkRoute
  DocsDesignDecisionsRoute: typeof DocsDesignDecisionsRoute
  DocsEqlRoute: typeof DocsEqlRoute
  DocsExamplesRoute: typeof DocsExamplesRoute
  DocsGpuEngineRoute: typeof DocsGpuEngineRoute
  DocsGuidesRoute: typeof DocsGuidesRoute
  DocsInstallationRoute: typeof DocsInstallationRoute
  DocsPerformanceRoute: typeof DocsPerformanceRoute
  DocsProjectHistoryRoute: typeof DocsProjectHistoryRoute
  DocsPythonSdkRoute: typeof DocsPythonSdkRoute
  DocsRoadmapRoute: typeof DocsRoadmapRoute
  DocsSecurityRoute: typeof DocsSecurityRoute
  DocsStorageRoute: typeof DocsStorageRoute
  DocsIndexRoute: typeof DocsIndexRoute
  DocsInternalsLockManagerRoute: typeof DocsInternalsLockManagerRoute
  DocsInternalsTransactionEngineRoute: typeof DocsInternalsTransactionEngineRoute
  DocsTutorialLessonRoute: typeof DocsTutorialLessonRoute
  DocsTutorialIndexRoute: typeof DocsTutorialIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsAdvancedRoute: DocsAdvancedRoute,
  DocsAlgorithmsRoute: DocsAlgorithmsRoute,
  DocsApiRoute: DocsApiRoute,
  DocsArchitectureRoute: DocsArchitectureRoute,
  DocsCliRoute: DocsCliRoute,
  DocsConfigurationRoute: DocsConfigurationRoute,
  DocsCoreConceptsRoute: DocsCoreConceptsRoute,
  DocsCppSdkRoute: DocsCppSdkRoute,
  DocsDesignDecisionsRoute: DocsDesignDecisionsRoute,
  DocsEqlRoute: DocsEqlRoute,
  DocsExamplesRoute: DocsExamplesRoute,
  DocsGpuEngineRoute: DocsGpuEngineRoute,
  DocsGuidesRoute: DocsGuidesRoute,
  DocsInstallationRoute: DocsInstallationRoute,
  DocsPerformanceRoute: DocsPerformanceRoute,
  DocsProjectHistoryRoute: DocsProjectHistoryRoute,
  DocsPythonSdkRoute: DocsPythonSdkRoute,
  DocsRoadmapRoute: DocsRoadmapRoute,
  DocsSecurityRoute: DocsSecurityRoute,
  DocsStorageRoute: DocsStorageRoute,
  DocsIndexRoute: DocsIndexRoute,
  DocsInternalsLockManagerRoute: DocsInternalsLockManagerRoute,
  DocsInternalsTransactionEngineRoute: DocsInternalsTransactionEngineRoute,
  DocsTutorialLessonRoute: DocsTutorialLessonRoute,
  DocsTutorialIndexRoute: DocsTutorialIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  ChatRoute: ChatRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  ContributingRoute: ContributingRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
